src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $movie_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $headline;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rating;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $lastUpdated;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duration;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $body;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $quote;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $class;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $cert;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sum;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Cast", mappedBy="movie_id")
     */
    private $casts;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="movie", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Genre", mappedBy="movie")
     */
    private $genres;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Reviewer", inversedBy="movies")
     */
    private $reviewAuthor;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $skyGoId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $skyGoUrl;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ViewingWindow")
     */
    private $viewingWindow;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Director", mappedBy="movie")
     */
    private $directors;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $friendlyUrl;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Video", mappedBy="movie")
     */
    private $videos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Gallery", mappedBy="movie")
     */
    private $galleries;


    public function __construct()
    {
        $this->casts = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->directors = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->galleries = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getMovieId(): ?string
    {
        return $this->movie_id;
    }

    public function setMovieId(string $movie_id): self
    {
        $this->movie_id = $movie_id;

        return $this;
    }

    public function getHeadline(): ?string
    {
        return $this->headline;
    }

    public function setHeadline(?string $headline): self
    {
        $this->headline = $headline;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getLastUpdated(): ?\DateTimeInterface
    {
        return $this->lastUpdated;
    }

    public function setLastUpdated(?\DateTimeInterface $lastUpdated): self
    {
        $this->lastUpdated = $lastUpdated;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getQuote(): ?string
    {
        return $this->quote;
    }

    public function setQuote(?string $quote): self
    {
        $this->quote = $quote;

        return $this;
    }

    public function getClass(): ?string
    {
        return $this->class;
    }

    public function setClass(?string $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function getCert(): ?string
    {
        return $this->cert;
    }

    public function setCert(?string $cert): self
    {
        $this->cert = $cert;

        return $this;
    }

    public function getSum(): ?string
    {
        return $this->sum;
    }

    public function setSum(?string $sum): self
    {
        $this->sum = $sum;

        return $this;
    }

    /**
     * @return Collection|Cast[]
     */
    public function getCasts(): Collection
    {
        return $this->casts;
    }

    public function addCast(Cast $cast): self
    {
        if (!$this->casts->contains($cast)) {
            $this->casts[] = $cast;
            $cast->addMovieId($this);
        }

        return $this;
    }

    public function removeCast(Cast $cast): self
    {
        if ($this->casts->contains($cast)) {
            $this->casts->removeElement($cast);
            $cast->removeMovieId($this);
        }

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setMovie($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getMovie() === $this) {
                $image->setMovie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
            $genre->addMovie($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genres->contains($genre)) {
            $this->genres->removeElement($genre);
            $genre->removeMovie($this);
        }

        return $this;
    }

    public function getReviewAuthor(): ?Reviewer
    {
        return $this->reviewAuthor;
    }

    public function setReviewAuthor(?Reviewer $reviewAuthor): self
    {
        $this->reviewAuthor = $reviewAuthor;

        return $this;
    }

    public function getSkyGoId(): ?string
    {
        return $this->skyGoId;
    }

    public function setSkyGoId(?string $skyGoId): self
    {
        $this->skyGoId = $skyGoId;

        return $this;
    }

    public function getSkyGoUrl(): ?string
    {
        return $this->skyGoUrl;
    }

    public function setSkyGoUrl(?string $skyGoUrl): self
    {
        $this->skyGoUrl = $skyGoUrl;

        return $this;
    }

    public function getViewingWindow(): ?ViewingWindow
    {
        return $this->viewingWindow;
    }

    public function setViewingWindow(?ViewingWindow $viewingWindow): self
    {
        $this->viewingWindow = $viewingWindow;

        return $this;
    }

    /**
     * @return Collection|Director[]
     */
    public function getDirectors(): Collection
    {
        return $this->directors;
    }

    public function addDirector(Director $director): self
    {
        if (!$this->directors->contains($director)) {
            $this->directors[] = $director;
            $director->addMovie($this);
        }

        return $this;
    }

    public function removeDirector(Director $director): self
    {
        if ($this->directors->contains($director)) {
            $this->directors->removeElement($director);
            $director->removeMovie($this);
        }

        return $this;
    }

    public function getFriendlyUrl(): ?string
    {
        return $this->friendlyUrl;
    }

    public function setFriendlyUrl(?string $friendlyUrl): self
    {
        $this->friendlyUrl = $friendlyUrl;

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setMovie($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {

src/Controller/MovieController.php
<?php

namespace App\Controller;

use App\Entity\Movie;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\Tools\Pagination\Paginator;

class MovieController extends AbstractController
{
	/**
     * @Route("/movies", name="movies")
     */
	public function movies()
	{
		// Redirect this URL to the paginated one
		return $this->redirectToRoute('movies_paginated', array('page' => 1));
	}

	/**
     * @Route("/movies/show/{slug}", name="show")
     */
	public function show($slug = null)
	{
		// Render template in case of not found error
		$errorRenderer = $this->render('movie/movie_show.html.twig', ['movie' => null]);
		
		// If there is no slug provided, return not found error
		if(!$slug) {
			$this->addFlash('danger', 'Movie not found!');
			return $errorRenderer;
		}

		// Get Movie Repository and search in the database
		$repository = $this->getDoctrine()->getRepository(Movie::class);
		$movie = $repository->findOneBy(['friendlyUrl' => $slug]);

		// If there is no result, return not found error
		if(!$movie) {
			$this->addFlash('danger', 'Movie not found!');
			return $errorRenderer;
		}
		
		// Cache images if it's first time to display them
		$images = $movie->getImages();
		$i = 0;
		foreach($images as $img) {
			// If local path is not set, it means it wasn't rendered yet and we need to cache it
			if(!$img->getLocalPath()) {
				$ext = pathinfo($img->getUrl(), PATHINFO_EXTENSION);
				if($img->getType() == 'card-image')
					$localPath = 'img/card-images/' . $movie->getMovieId() . "_" . $i . "." . $ext;
				if($img->getType() == 'keyart-image')
					$localPath = 'img/keyart-images/' . $movie->getMovieId() . "_" . $i . "." . $ext;
				
				// Check if the URL requested is available
				$HTTPHeaders = get_headers($img->getUrl());
				if(substr($HTTPHeaders[0], 9, 3) == '200') {
					// Set local path and copy the image locally
					$img->setLocalPath($localPath);
					file_put_contents($localPath, file_get_contents($img->getUrl()));
					$i++;
				}
			}
		}

		// Cache videos if it's first time to display them
		$videos = $movie->getVideos();
		$i = 0;
		foreach($videos as $video) {
			// If local path is not set, it means it wasn't rendered yet and we need to cache it
			if(!$video->getLocalPath()) {
				$ext = pathinfo($img->getUrl(), PATHINFO_EXTENSION);
				$localPath = 'video/' . $movie->getMovieId() . "_" . $i . "." . $ext;
				
				// Check if the URL requested is available
				$HTTPHeaders = get_headers($video->getUrl());
				if(substr($HTTPHeaders[0], 9, 3) == '200') {
					// Set local path and copy the image locally
					$video->setLocalPath($localPath);
					file_put_contents($localPath, file_get_contents($video->getUrl()));
					$i++;
				}
			}
		}
		// Update the database
		$this->getDoctrine()->getManager()->flush();
		
		return $this->render('movie/movie_show.html.twig', [
			'movie' => $movie,
        ]);
	}
	
	/**
     * @Route("/movies/page/{page<\d+>}", name="movies_paginated")
     */
    public function movies_paginated($page = 1)
    {
		if (!is_numeric($page) || $page < 1) $page = 1;
		$perpage = 5;

		// Query for the paginated results
		$qb = $this->getDoctrine()->getManager()->createQueryBuilder();
		$qb->select('m')
			->from('App\Entity\Movie', 'm')
			->orderBy('m.year', "DESC")
			->setFirstResult(($page - 1) * $perpage)
			->setMaxResults($perpage);
		$movies = $qb->getQuery()->getResult();

		// Count all results
		$qb = $this->getDoctrine()->getManager()->createQueryBuilder()
            ->select("COUNT(m.id)")
            ->from('App\Entity\Movie', "m");
		$count = $qb->getQuery()->getSingleScalarResult();

		// Set variables needed for pagination
		$totalPages = floor((($count - 1) / $perpage) + 1);
		$link = '/movies/page/';

        return $this->render('movie/movie_list.html.twig', [
			'movies' => $movies,
			'total' => $totalPages,
			'perpage' => $perpage,
			'page' => $page,
			'link' => $link,
        ]);
	}

	/**
     * @Route("/movies/search/{slug}/page/{page<\d+>}", name="movies_search_paginated")
     */
    public function movies_search_paginated($slug = null, $page = 1)
    {
		if (!is_numeric($page) || $page < 1) $page = 1;
		$perpage = 5;
		$search = "%".$slug."%";

		// Query for the paginated results
		$qb = $this->getDoctrine()->getManager()->createQueryBuilder();
		$qb->select('m')
			->from('App\Entity\Movie', 'm')
			->where('m.headline LIKE :search')
			->orderBy('m.year', "DESC")
			->setParameter("search", $search)
			->setFirstResult(($page - 1) * $perpage)
			->setMaxResults($perpage);
		$movies = $qb->getQuery()->getResult();

		// Count all results
		$qb = $this->getDoctrine()->getManager()->createQueryBuilder()
			->select("COUNT(m.id)")
			->where('m.headline LIKE :search')
			->from('App\Entity\Movie', "m")
			->setParameter("search", $search);
		$count = $qb->getQuery()->getSingleScalarResult();

		// Set variables needed for pagination
		$totalPages = floor((($count - 1) / $perpage) + 1);
		$link = '/movies/search/' . $slug . '/page/';

        return $this->render('movie/movie_list.html.twig', [
			'movies' => $movies,
			'total' => $totalPages,
			'perpage' => $perpage,
			'page' => $page,
			'link' => $link,
        ]);
	}

	/**
     * @Route("/movies/search/{slug}", name="movies_search_partial")
     */
    public function movies_search_partial($slug = null)
    {
		// Redirect this URL to the paginated one
		return $this->redirectToRoute('movies_search_paginated', array('slug' => $slug, 'page' => 1));
	}
}

templates/movie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/MovieController.php'|file_link(0) }}">src/Controller/MovieController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/movie/index.html.twig'|file_link(0) }}">templates/movie/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/movie/movie_show.html.twig
{% extends 'base_table.html.twig' %}

{% block title %}Movie Database{% endblock %}

{% block stylesheets %}
    <!-- Fontfaces CSS-->
    <link href="/css/font-face.css" rel="stylesheet" media="all">
    <link href="/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="/css/theme.css" rel="stylesheet" media="all">
	<link href="/css/custom.css" rel="stylesheet" media="all">
{% endblock %}

{% block searchbox %}
	<div class="form-header">
		<input class="au-input au-input--xl" type="text" name="search" id="searchField" placeholder="Search movies ..." />
		<button class="au-btn--submit" type="submit" id="search">
			<i class="zmdi zmdi-search"></i>
		</button>
	</div>
{% endblock %}

{% block pageTitle %}Movie Info{% endblock %}

{% block body %}
<div class="row">
	<div class="col-md-12">
		<div class="table-responsive table-responsive-data2">
			{% if movie %}
				<div class="au-card">
					<div class="au-card-inner">
						
						<h3 class="title-2 tm-b-5 font-weight-bold">
							{{ movie.headline }} <small>({{ movie.year }})</small>
							&nbsp;&nbsp;<span class="badge badge-secondary">{{ movie.duration / 60 }} mins</span>
							{% if movie.rating %}&nbsp;&nbsp;<span class="badge badge-success">{{ movie.rating }}&nbsp;<i class="fas fa-star"></i></span>{% endif %}
							&nbsp;&nbsp;<span class="badge badge-info">cert {{ movie.cert }}</span>
						</h3>
						<div class="row mt-4">
							<div class="col-md-6">
								<div class="card">
									<div class="card-header">Director(s)</div>
									<div class="card-body">
										{% for director in movie.getDirectors %}
											{{ director.name }}{% if not loop.last %},&nbsp;{% endif %}
										{% endfor %}
									</div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="card">
									<div class="card-header">Cast</div>
									<div class="card-body">
										{% for cast in movie.getCasts %}
											{{ cast.name }}{% if not loop.last %},&nbsp;{% endif %}
										{% endfor %}
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<h4>Genres:&nbsp;
								<small class="text-muted">
									{% for genre in movie.getGenres %}
										{{ genre.name }}{% if not loop.last %},&nbsp;{% endif %}
									{% endfor %}
								</small>
							</h4>
						</div>
						<div class="row mt-4 no-gutter">
							<div class="col-xl-6 pl-0">
								<h4 class="mb-2">Synopsis</h4>
								<p class="pl-3 text-justify">{{ movie.synopsis }}</p>
							</div>
							<div class="col-xl-6 pl-0">
								{% if movie.quote %}
									<h4 class="mb-2">Quote</h4>
									<blockquote class="pl-3">
										<i class="fas fa-quote-left"></i> {{ movie.quote }} <i class="fas fa-quote-right"></i>
									</blockquote>
								{% endif %}
							</div>
						</div>
						<div class="row mt-4">
							<h4 class="mb-2">Review{% if movie.reviewAuthor %}<small class="font-italic"> by {{ movie.reviewAuthor.name }}</small>{% endif %}</h4>
							<p class="pl-3 pr-3 mt-1 text-justify">{{ movie.body }}</p>
						</div>
						<div class="float-right"><a href="{{ movie.url }}" target="_blank">Source</a></div>
						<div class="clearfix"></div>
						<div class="float-right font-italic mt-2">Last updated: {{ movie.lastUpdated|date("m/d/Y") }}</div>

						<div class="row mt-4">
							<div class="card">
								<div class="card-header">Other info</div>
								<div class="card-body">
									Class: {{ movie.class }}<br />
									ID: {{ movie.movieId }}<br />
									Sum: {{ movie.sum }}<br />
									{% if movie.skyGoId %}Sky Go ID: {{ movie.skyGoId }}<br />{% endif %}
									{% if movie.skyGoUrl %}Sky Go URL: <a href="{{ movie.skyGoUrl }}" target="_blank">Here</a><br />{% endif %}
								</div>
							</div>
						</div>
						<div class="row mt-2">
							{% if movie.getViewingWindow %}
								<div class="card">
									<div class="card-header">Viewing window</div>
									<div class="card-body">
										{% if movie.getViewingWindow.title %}Title: {{ movie.getViewingWindow.title }}<br />{% endif %}
										{% if movie.getViewingWindow.startDate %}Start date: {{ movie.getViewingWindow.startDate|date("m/d/Y") }}<br />{% endif %}
										{% if movie.getViewingWindow.endDate %}End date: {{ movie.getViewingWindow.endDate|date("m/d/Y") }}<br />{% endif %}
										{% if movie.getViewingWindow.wayToWatch %}Way to watch: {{ movie.getViewingWindow.wayToWatch }}{% endif %}
									</div>
								</div>
							{% endif %}
						</div>
						{% if movie.getImages|length %}
							<div class="row mt-4 no-gutter"><h4 class="mb-4">Card Images</h4></div>
							<div class="row mt-2 no-gutter">
								{% for image in movie.getImages %}
									{% if image.type == 'card-image' and image.localPath %}
										<div class="col-xl-2 mt-3">
											<img src="/{{ image.localPath }}" style="height:100px !important" />	
										</div>
									{% endif %}
								{% endfor %}
							</div>
							<div class="row mt-4 no-gutter"><h4 class="mb-4">Key Art Images</h4></div>
							<div class="row mt-2 no-gutter">
								{% for image in movie.getImages %}
									{% if image.type == 'keyart-image' and image.localPath %}
										<div class="col-xl-2 mt-3">
											<img src="/{{ image.localPath }}" style="height:100px !important" />	
										</div>
									{% endif %}
								{% endfor %}
							</div>
						{% endif %}
						{% if movie.getVideos|length %}
							<div class="row mt-4 no-gutter"><h4 class="mb-4">Videos</h4></div>
							<div class="row mt-1 no-gutter">
								<ul class="pl-5">
									{% for video in movie.getVideos %}
										{% if video.localPath %}
											<li>
												<video width="400" controls>
													<source src="{{ video.localPath }}" type="video/mp4">
													Your browser does not support HTML5 video.
												</video>
											</li>
										{% else %}
											<li>This video coudn't be downloaded. Try navigating to&nbsp;
											<a href="{{ video.url }}" target="_blank">{{ video.title }}</a> - {{ video.quality }} quality</li>
										{% endif %}
									{% endfor %}
								</ul>
							</div>
						{% endif %}
						{% if movie.getGalleries|length %}
							<div class="row mt-4 no-gutter"><h4 class="mb-4">Galleries</h4></div>
							<div class="row mt-1 no-gutter">
								<ul class="pl-5">
									{% for gallery in movie.getGalleries %}
										<li><a href="{{ gallery.url }}" target="_blank">{{ gallery.title }}</a></li>
									{% endfor %}
								</ul>
							</div>
						{% endif %}
					</div>
				</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}
{% block javascripts %}
	<!-- Jquery JS-->
    <script src="/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="/vendor/slick/slick.min.js">
    </script>
    <script src="/vendor/wow/wow.min.js"></script>
    <script src="/vendor/animsition/animsition.min.js"></script>
    <script src="/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="/vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="/js/main.js"></script>
	<script src="/js/custom.js"></script>
{% endblock %}